CREATE TABLE `influx_cfg` (`id` TEXT NULL, `host` TEXT NULL, `port` INTEGER NULL, `db` TEXT NULL, `user` TEXT NULL, `password` TEXT NULL, `retention` TEXT NULL);
CREATE UNIQUE INDEX `UQE_influx_cfg_id` ON `influx_cfg` (`id`);
CREATE TABLE `snmp_device_cfg` (`id` TEXT NULL, `host` TEXT NULL, `port` INTEGER NULL, `retries` INTEGER NULL, `timeout` INTEGER NULL, `repeat` INTEGER NULL, `snmpversion` TEXT NULL, `community` TEXT NULL, `v3seclevel` TEXT NULL, `v3authuser` TEXT NULL, `v3authpass` TEXT NULL, `v3authprot` TEXT NULL, `v3privpass` TEXT NULL, `v3privprot` TEXT NULL, `freq` INTEGER NULL, `outdb` TEXT NULL, `loglevel` TEXT NULL, `logfile` TEXT NULL, `snmpdebug` INTEGER NULL, `devicetagname` TEXT NULL, `devicetagvalue` TEXT NULL, `extra-tags` TEXT NULL, `location` TEXT NULL);
CREATE UNIQUE INDEX `UQE_snmp_device_cfg_id` ON `snmp_device_cfg` (`id`);
CREATE TABLE `snmp_metric_cfg` (`id` TEXT NULL, `field_name` TEXT NULL, `description` TEXT NULL, `baseoid` TEXT NULL, `datasrctype` TEXT NULL, `getrate` INTEGER NULL, `scale` REAL NULL, `shift` REAL NULL, `istag` INTEGER NULL DEFAULT 0);
CREATE UNIQUE INDEX `UQE_snmp_metric_cfg_id` ON `snmp_metric_cfg` (`id`);
CREATE TABLE `influx_measurement_cfg` (`id` TEXT NULL, `name` TEXT NULL, `getmode` TEXT NULL, `indexoid` TEXT NULL, `indextag` TEXT NULL, `indexasvalue` INTEGER NULL DEFAULT 0);
CREATE UNIQUE INDEX `UQE_influx_measurement_cfg_id` ON `influx_measurement_cfg` (`id`);
CREATE TABLE `meas_filter_cfg` (`id` TEXT NULL, `id_measurement_cfg` TEXT NULL, `filter_type` TEXT NULL, `file_name` TEXT NULL, `enable_alias` INTEGER NULL, `cond_oid` TEXT NULL, `cond_type` TEXT NULL, `cond_value` TEXT NULL);
CREATE UNIQUE INDEX `UQE_meas_filter_cfg_id` ON `meas_filter_cfg` (`id`);
CREATE TABLE `measurement_field_cfg` (`id_measurement_cfg` TEXT NULL, `id_metric_cfg` TEXT NULL);
CREATE TABLE `m_groups_cfg` (`id` TEXT NULL);
CREATE UNIQUE INDEX `UQE_m_groups_cfg_id` ON `m_groups_cfg` (`id`);
CREATE TABLE `m_groups_measurements` (`id_mgroup_cfg` TEXT NULL, `id_measurement_cfg` TEXT NULL);
CREATE TABLE `snmp_dev_m_groups` (`id_snmpdev` TEXT NULL, `id_mgroup_cfg` TEXT NULL);
CREATE TABLE `snmp_dev_filters` (`id_snmpdev` TEXT NULL, `id_filter` TEXT NULL);
