on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release Packages

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Go Binary
        run: |
          go run build.go build
      - name: Install Node/NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.1'
      - name: Build Frontend 
        run: |
          npm install
          PATH=$(npm bin):$PATH
          ng build --prod
      - name: Install FPM
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
      - name: Build Packages 
        run: |
          go run build.go pkg-all
          packaging/get-changelog.sh  ${{ steps.branch_name.outputs.SOURCE_TAG }} > ${{ github.workspace }}-CHANGELOG.txt
          cat ${{ github.workspace }}-CHANGELOG.txt
          VERSION=`echo ${{ steps.branch_name.outputs.SOURCE_TAG }}| sed 's/v//g'`
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Upload Releases Asset  (RPM/DEB)
        id: upload-release-asset
        uses: softprops/action-gh-release@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.branch_name.outputs.SOURCE_TAG }} 
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            LICENSE
            dist/snmpcollector-${{ env.version }}-1.x86_64.rpm
            dist/snmpcollector-${{ env.version }}-1.x86_64.rpm.sha1
            dist/snmpcollector_${{ env.version }}_amd64.deb
            dist/snmpcollector_${{ env.version }}_amd64.deb.sha1

